# Generated by Django 3.0.7 on 2020-06-28 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20200620_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_read',
            field=models.ManyToManyField(related_name='read', to=settings.AUTH_USER_MODEL),
        ),
    ]
